services:
  postgres:
    image: postgres:15rc1-alpine
    environment:
      POSTGRES_USER: pact_broker
      POSTGRES_PASSWORD: letmein!
      POSTGRES_DB: pact_broker
  
  # Database details host=database, username=postgres, password=letmetin!
  # Access pgadmin using http://localhost:8082
  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: letmein!
    ports:
      - "8082:80"

  pact-broker:
    image: pactfoundation/pact-broker
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_USERNAME: pact_broker
      PACT_BROKER_DATABASE_PASSWORD: letmein!
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact_broker
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: 5
      PACT_BROKER_PORT: 9292
      PACT_BROKER_BASE_URL: 'http://localhost http://localhost:9292'
    ports:
      - "9292:9292"

  greeting-api:
    build: .
    depends_on:
      - pact-broker
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: http://+:5001
    
